import Head from 'next/head'
import Image from 'next/image'
import data from '../data/data';
import Link from 'next/link';



export default function Home() {
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <div>
          {data.map((item)=>(
            <div className="card" key={item.id}>
            <div className="card-img"><Image src={item.image} alt={item.id} width="300" height="200" ></Image></div>
            <div className="card-title">{item.title}</div>
            <div><Link href={`/blog/${item.id}`}><h2>{item.title}</h2></Link></div>
         </div>    
            ))}
        </div>
     
    </div>
  )
}
